routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Duo2faController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\ShowActivityLogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy-policy', function () {
    return view('policy');
});

Route::get('/terms-of-service', function () {
    return view('terms');
});

/* SOCIAL LOGIN ROUTES */
Route::get('social-login/{provider}', [SocialLoginController::class, 'redirect_to_provider'])->name('social-login.redirect');
Route::get('social-login/{provider}/callback', [SocialLoginController::class, 'callback_from_provider'])->name('social-login.callback');

Route::group(['middleware' => ['auth:sanctum', 'verified']], function () {
    /* DUO 2FA ROUTES */
    Route::get('/duo-2fa', [Duo2faController::class, 'resolve_duo_sign_request'])->name('duo.2fa');
    Route::post('/duo-2fa', [Duo2faController::class, 'resolve_duo_post_action']);

    Route::group(['middleware' => ['duo.2fa']], function () {
        /* DASHBOARD */
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        /* USER ROUTES */
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('user', UserController::class);

        /* ACTIVITY LOG ROUTES */
        Route::get('activity-log', [ShowActivityLogController::class, 'index'])->name('activity-log.index');
        Route::get('activity-log/data', [ShowActivityLogController::class, 'data'])->name('activity-log.data');

        /* ROLE ROUTES */
        Route::get('role/data', [RoleController::class, 'data'])->name('role.data');
        Route::resource('role', RoleController::class);

        /* TASK ROUTES */
        Route::get('task/data', [TaskController::class, 'data'])->name('task.data');
        Route::resource('task', TaskController::class)->middleware('subscription.check');

        Route::get('subscription/payment', [SubscriptionController::class, 'subscription_payment'])->name('subscription.payment');
        Route::post('subscription/store', [SubscriptionController::class, 'subscription_store'])->name('subscription.store');
    });
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/action.blade.php
<div>
    @can("edit_$data->model")
        @if ($data->model == 'task')
            <a href="javascript:void(0)" data-id="{{ $data->user->id }}" class="btn btn-info btn-sm text-white kf_menu_edit">{{ __('Edit') }}</a>
        @else
            <a class="btn btn-info btn-sm text-white" href="{{ route($data->edit_url, $data->user->id) }}">
                {{ __('Edit') }}
            </a>
        @endif
    @endcan
    
    @can("delete_$data->model")
        @if ($data->model != 'user' || ($data->model == 'user' && auth()->id() != $data->user->id))
            <a class="sa-delete btn btn-danger btn-sm text-white" data-form-id="{{ $data->model.'-delete-form_'.$data->user->id }}">
                {{ __('Delete') }}
            </a>
            <form method="POST" id="{{ $data->model.'-delete-form_'.$data->user->id }}" action="{{ route($data->delete_url, $data->user->id) }}">
                @csrf
                @method('DELETE')
            </form>
        @endif
    @endcan
</div>

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <x-jet-welcome />
</x-app-layout>

resources/views/message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
  
@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
   
@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif
   
@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
</div>
@endif

resources/views/navigation-menu.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white border-bottom sticky-top">
    <div class="container">
        <!-- Logo -->
        <a class="navbar-brand" href="/">
            <x-jet-application-mark width="36" />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <x-jet-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                    {{ __('Dashboard') }}
                </x-jet-nav-link>
                @can('show_user')
                    <x-jet-nav-link href="{{ route('user.index') }}" :active="request()->routeIs('user.index') || request()->routeIs('user.create') || request()->routeIs('user.edit')">
                        {{ __('User') }}
                    </x-jet-nav-link>
                @endcan
                @can('show_activity_log')
                    <x-jet-nav-link href="{{ route('activity-log.index') }}" :active="request()->routeIs('activity-log.index')">
                        {{ __('Activity Log') }}
                    </x-jet-nav-link>
                @endcan
                @can('show_role')
                    <x-jet-nav-link href="{{ route('role.index') }}" :active="request()->routeIs('role.index') || request()->routeIs('role.create') || request()->routeIs('role.edit')">
                        {{ __('Role') }}
                    </x-jet-nav-link>
                @endcan
                @can('show_task')
                    <x-jet-nav-link href="{{ route('task.index') }}" :active="request()->routeIs('task.index') || request()->routeIs('task.create') || request()->routeIs('task.edit')">
                        {{ __('Task') }}
                    </x-jet-nav-link>
                @endcan
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto align-items-baseline">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <x-jet-dropdown id="teamManagementDropdown">
                        <x-slot name="trigger">
                            {{ Auth::user()->currentTeam->name }}

                            <svg class="ml-2" width="18" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                            </svg>
                        </x-slot>

                        <x-slot name="content">
                            <!-- Team Management -->
                            <h6 class="dropdown-header">
                                {{ __('Manage Team') }}
                            </h6>

                            <!-- Team Settings -->
                            <x-jet-dropdown-link href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">
                                {{ __('Team Settings') }}
                            </x-jet-dropdown-link>

                            @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                <x-jet-dropdown-link href="{{ route('teams.create') }}">
                                    {{ __('Create New Team') }}
                                </x-jet-dropdown-link>
                            @endcan

                            <hr class="dropdown-divider">

                            <!-- Team Switcher -->
                            <h6 class="dropdown-header">
                                {{ __('Switch Teams') }}
                            </h6>

                            @foreach (Auth::user()->allTeams() as $team)
                                <x-jet-switchable-team :team="$team" />
                            @endforeach
                        </x-slot>
                    </x-jet-dropdown>
                @endif

                <!-- Settings Dropdown -->
                @auth
                    <x-jet-dropdown id="settingsDropdown">
                        <x-slot name="trigger">
                            @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                                <img class="rounded-circle" width="32" height="32" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                            @else
                                {{ Auth::user()->name }}
                            @endif

                            <svg class="ml-2 d-none" width="18" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z" clip-rule="evenodd" />
                            </svg>
                        </x-slot>

                        <x-slot name="content">
                            <!-- Account Management -->
                            <h6 class="dropdown-header small text-muted">
                                {{ __('Manage Account') }}
                            </h6>

                            <x-jet-dropdown-link href="{{ route('profile.show') }}">
                                {{ __('Profile') }}
                            </x-jet-dropdown-link>

                            @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                                <x-jet-dropdown-link href="{{ route('api-tokens.index') }}">
                                    {{ __('API Tokens') }}
                                </x-jet-dropdown-link>
                            @endif

                            <hr class="dropdown-divider">

                            <!-- Authentication -->
                            <x-jet-dropdown-link href="{{ route('logout') }}"
                                                 onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </x-jet-dropdown-link>
                            <form method="POST" id="logout-form" action="{{ route('logout') }}">
                                @csrf
                            </form>
                        </x-slot>
                    </x-jet-dropdown>
                @endauth
            </ul>
        </div>
    </div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="row justify-content-center pt-4">
        <div class="col-6">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="card shadow-sm">
                <div class="card-body">
                    {{-- {!! $policy !!} --}}
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident adipisci at necessitatibus, doloremque ipsum illum sunt nam debitis alias similique ab. Nihil neque temporibus sunt minus totam voluptatem magnam.
                </div>
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="row justify-content-center pt-4">
        <div class="col-6">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="card shadow-sm">
                <div class="card-body">
                    {{-- {!! $terms !!} --}}
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam provident adipisci at necessitatibus, doloremque ipsum illum sunt nam debitis alias similique ab. Nihil neque temporibus sunt minus totam voluptatem magnam.
                </div>
            </div>
        </div>
    </div>
</x-guest-layout>