routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Duo2faController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\ShowActivityLogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy-policy', function () {
    return view('policy');
});

Route::get('/terms-of-service', function () {
    return view('terms');
});

/* SOCIAL LOGIN ROUTES */
Route::get('social-login/{provider}', [SocialLoginController::class, 'redirect_to_provider'])->name('social-login.redirect');
Route::get('social-login/{provider}/callback', [SocialLoginController::class, 'callback_from_provider'])->name('social-login.callback');

Route::group(['middleware' => ['auth:sanctum', 'verified']], function () {
    /* DUO 2FA ROUTES */
    Route::get('/duo-2fa', [Duo2faController::class, 'resolve_duo_sign_request'])->name('duo.2fa');
    Route::post('/duo-2fa', [Duo2faController::class, 'resolve_duo_post_action']);

    Route::group(['middleware' => ['duo.2fa']], function () {
        /* DASHBOARD */
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        /* USER ROUTES */
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('user', UserController::class);

        /* ACTIVITY LOG ROUTES */
        Route::get('activity-log', [ShowActivityLogController::class, 'index'])->name('activity-log.index');
        Route::get('activity-log/data', [ShowActivityLogController::class, 'data'])->name('activity-log.data');

        /* ROLE ROUTES */
        Route::get('role/data', [RoleController::class, 'data'])->name('role.data');
        Route::resource('role', RoleController::class);

        /* TASK ROUTES */
        Route::get('task/data', [TaskController::class, 'data'])->name('task.data');
        Route::resource('task', TaskController::class)->middleware('subscription.check');

        Route::get('subscription/payment', [SubscriptionController::class, 'subscription_payment'])->name('subscription.payment');
        Route::post('subscription/store', [SubscriptionController::class, 'subscription_store'])->name('subscription.store');
    });
});

app/Models/Task.php
<?php

namespace App\Models;

use stdClass;
use App\Models\User;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'description', 'is_completed', 'user_id'];

    /**
     * A task is belongs to an user
     *
     * @return void
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    /**
     * Display is_completed in formattd way.
     *
     * @param  \App\Task
     * @return  string
     */
    public static function laratablesIsCompleted($task)
    {
        return $task->is_completed == 'yes' ? "<span class='badge badge-success'>" . strtoupper($task->is_completed) . "</span>" : "<span class='badge badge-danger'>" . strtoupper($task->is_completed) . "</span>";
    }

    /**
     * Returns the action Column html for datatables.
     *
     * @param  \App\Task
     * @return  string
     */
    public static function laratablesCustomAction($task)
    {
        $data = new stdClass();
        $data->user = $task;
        $data->model = 'task';
        $data->edit_url = 'task.edit';
        $data->delete_url = 'task.destroy';
        return view('action', compact('data'))->render();
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Notifications\TaskNotification;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Notification;
use Symfony\Component\HttpFoundation\Response;
use NotificationChannels\MicrosoftTeams\MicrosoftTeamsChannel;

class TaskController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:add_task', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_task',   ['only' => ['edit', 'update']]);
        $this->middleware('permission:show_task',   ['only' => ['show', 'index']]);
        $this->middleware('permission:delete_task',   ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('task.index');
    }

    /**
     * return a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function data()
    {
        return Laratables::recordsOf(Task::class);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('task.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'title' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
        ])->validate();

        $task = Task::create([
            'title' => $request->title,
            'description' => $request->description,
            'is_completed' => $request->is_completed,
            'user_id' => Auth::id(),
        ]);

        Notification::route('nexmo', Auth::user()->phone_number ?? '+880 1642 157515')
            ->route('mail', Auth::user()->email ?? 'taylor@example.com')
            ->route('slack', env('SLACK_HOOK_URL'))
            ->route(MicrosoftTeamsChannel::class, env('TEAMS_WEBHOOK_URL'))
            ->notify(new TaskNotification($task));

        return redirect()->route('task.index')->with('success', 'A new task created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        if (request()->ajax()) {
            return response()->json(['task' => $task], Response::HTTP_OK);
        }
        return view('task.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        $task = Task::with('user')->where('id', $task->id)->first();
        return view('task.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        Validator::make($request->all(), [
            'title' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
        ])->validate();

        $task->title = $request->title;
        $task->description = $request->description;
        $task->is_completed = $request->is_completed;

        $task->save();

        if ($request->ajax()) {
            return response()->json(['task' => $task], Response::HTTP_ACCEPTED);
        }

        return redirect()->route('task.index')->with('success', 'Task information updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Task  $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        $task->delete();

        return redirect()->route('task.index')->with('success', 'Task information deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/task/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Create Task') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card-body">
                <form method="POST" action="{{ route('task.store') }}">
                    @csrf
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Title') }}" />
        
                        <x-jet-input class="{{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title"
                                     :value="old('title')" required autofocus autocomplete="title" />
                        <x-jet-input-error for="title"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Description') }}" />
                        <textarea name="description" id="description" rows="3" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" required>{{old('description')}}</textarea>
                        <x-jet-input-error for="description"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="yes" value="yes" name="is_completed" class="custom-control-input">
                            <label class="custom-control-label" for="yes">YES</label>
                          </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="no" value="no" name="is_completed" class="custom-control-input" checked>
                            <label class="custom-control-label" for="no">NO</label>
                          </div>
                    </div>
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('task.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/task/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit Task') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card-body">
                <form method="POST" action="{{ route('task.update', $task->id) }}">
                    @csrf
                    @method('PUT')
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Title') }}" />
        
                        <x-jet-input class="{{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title"
                                     :value="$task->title ?? old('title')" required autofocus autocomplete="title" />
                        <x-jet-input-error for="title"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Description') }}" />
                        <textarea name="description" id="description" rows="3" class="form-control {{ $errors->has('description') ? 'is-invalid' : '' }}" required>{{$task->description ?? old('description')}}</textarea>
                        <x-jet-input-error for="description"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="yes" value="yes" name="is_completed" class="custom-control-input" {{ $task->is_completed == 'yes' ? 'checked' : ''}}>
                            <label class="custom-control-label" for="yes">YES</label>
                          </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="no" value="no" name="is_completed" class="custom-control-input" {{ $task->is_completed == 'no' ? 'checked' : ''}}>
                            <label class="custom-control-label" for="no">No</label>
                          </div>
                    </div>
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('task.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/task/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Task List') }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-12 align-self-end">
            <a class="btn btn-primary" href="{{ route('task.create') }}">
                {{ __('Create Task') }}
            </a>
        </div>
        <div class="col-12">
            <div class="mt-4">
                <table id="basic-laratable" class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Is Completed?</th>
                            <th>User</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="taskEditModal" tabindex="-1" role="dialog" aria-labelledby="taskEditModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Edit Task</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                <form action="" method="POST">
                    <div class="d-none alert alert-danger">
                        <ul class="kf_error">

                        </ul>
                    </div>

                    <div class="form-group d-none">
                        <label>Task ID<span class="required">*</span></label>
                        <div>
                            <input type="hidden" name="task_id" id="kf_task_id" class="form-control" placeholder="Task id" required/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label>Task Title<span class="required">*</span></label>
                        <div>
                            <input type="text" name="title" id="kf_title" class="form-control" placeholder="Task name" required/>
                        </div>
                    </div>

                    <div class="form-group" id="link-box">
                        <label>Description</label>
                        <div>
                            <textarea name="description" id="kf_description" rows="3" class="form-control" required></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="kf_yes" value="yes" name="is_completed" class="custom-control-input">
                            <label class="custom-control-label" for="kf_yes">YES</label>
                          </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="kf_no" value="no" name="is_completed" class="custom-control-input">
                            <label class="custom-control-label" for="kf_no">No</label>
                          </div>
                    </div>

                    <div class="form-group mb-0">
                        <div>
                            <button type="button" id="kf_submit" class="btn btn-primary waves-effect waves-light mr-1">
                                Submit
                            </button>

                            <button data-dismiss="modal" aria-label="Close" class="btn btn-secondary waves-effect">
                                Cancel
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        </div>
    </div>
    

    @push('style')
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    @push('scripts')
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

        <script>
            $(document).ready(function () {
                $.noConflict();
                $("#basic-laratable").DataTable({
                    serverSide: true,
                    ajax: "{{ route('task.data') }}",
                    columns: [
                        { name: 'title' },
                        { name: 'description', orderable: false },
                        { name: 'is_completed' },
                        { name: 'user.name', orderable: false},
                        { name: 'created_at'},
                        { name: 'action', orderable: false, searchable:false},
                    ],
                });

                $(document).on('click', '.kf_menu_edit', function () {
                    $('.kf_error').parent().addClass('d-none');

                    let task_id = $(this).data('id');

                    axios.get(`/task/${task_id}`).then((res) => {
                        let data = res.data.task;
                        $('#kf_task_id').val(data.id);
                        $('#kf_title').val(data.title);
                        $('#kf_description').val(data.description);
                        if (data.is_completed == 'yes') {
                            $("#kf_yes").attr("checked", "checked");
                        } else {
                            $("#kf_no").attr("checked", "checked");
                        }

                        $("#taskEditModal").modal('show');
                    })
                })
                
                $(document).on('click', '#kf_submit', function () {
                    let task_id = $('#kf_task_id').val();
                    let data = {
                        'parent': $('#kf_parent').val(),			
                        'title': $('#kf_title').val(),			
                        'description': $('#kf_description').val(),			
                        'is_completed': $('input:checked').val(),			
                    };
                    console.log(data);

                    axios.put(`/task/${task_id}`, data).then((res) => {
                        Swal.fire({
                            title: "Updated?",
                            text: "Task updated successfully!",
                            type: "warning",
                            showCancelButton: false,
                            confirmButtonColor: "#02a499",
                            confirmButtonText: "Ok!"
                        }).then(function (result) {
                            window.location.reload();
                        });
                    }).catch((err)=>{
                        let li = '';
                        let errors = err.response.data.errors;
                        for (const key in errors) {
                            if (Object.hasOwnProperty.call(errors, key)) {
                                const element = errors[key];
                                li += `<li>${element[0]}</li>`;
                            }
                        }
                        $('.kf_error').parent().removeClass('d-none').html(li);
                    });
                });
            });
        </script>
    @endpush
</x-app-layout>

resources/views/task/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('View Task') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card-body">
                <div class="h4">{{ $task->title }}</div>
                <p>{{$task->description }}</p>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-end align-items-baseline">
                    <a class="btn btn-danger" href="{{ route('task.index') }}">
                        {{ __('Back') }}
                    </a>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>