routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Duo2faController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\ShowActivityLogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy-policy', function () {
    return view('policy');
});

Route::get('/terms-of-service', function () {
    return view('terms');
});

/* SOCIAL LOGIN ROUTES */
Route::get('social-login/{provider}', [SocialLoginController::class, 'redirect_to_provider'])->name('social-login.redirect');
Route::get('social-login/{provider}/callback', [SocialLoginController::class, 'callback_from_provider'])->name('social-login.callback');

Route::group(['middleware' => ['auth:sanctum', 'verified']], function () {
    /* DUO 2FA ROUTES */
    Route::get('/duo-2fa', [Duo2faController::class, 'resolve_duo_sign_request'])->name('duo.2fa');
    Route::post('/duo-2fa', [Duo2faController::class, 'resolve_duo_post_action']);

    Route::group(['middleware' => ['duo.2fa']], function () {
        /* DASHBOARD */
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        /* USER ROUTES */
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('user', UserController::class);

        /* ACTIVITY LOG ROUTES */
        Route::get('activity-log', [ShowActivityLogController::class, 'index'])->name('activity-log.index');
        Route::get('activity-log/data', [ShowActivityLogController::class, 'data'])->name('activity-log.data');

        /* ROLE ROUTES */
        Route::get('role/data', [RoleController::class, 'data'])->name('role.data');
        Route::resource('role', RoleController::class);

        /* TASK ROUTES */
        Route::get('task/data', [TaskController::class, 'data'])->name('task.data');
        Route::resource('task', TaskController::class)->middleware('subscription.check');

        Route::get('subscription/payment', [SubscriptionController::class, 'subscription_payment'])->name('subscription.payment');
        Route::post('subscription/store', [SubscriptionController::class, 'subscription_store'])->name('subscription.store');
    });
});

app/Models/Role.php
<?php

namespace App\Models;

use stdClass;
use App\Models\User;
use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends SpatieRole
{
    use HasFactory;

    /**
     * Mutates the role name before storing into the DB
     * 
     * @param $value
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucwords($value);
    }

    /**
     * @return array
     */
    public static function availableRoles()
    {
        return [
            'Super Admin' // You can add as many roles here also for seeding
        ];
    }

    /**
     * Created user belongs to User
     *
     * @return void
     */
    public function created_user()
    {
        return $this->belongsTo(User::class, 'created_by', 'id');
    }

    /**
     * Updated user belongs to User
     *
     * @return void
     */
    public function updated_user()
    {
        return $this->belongsTo(User::class, 'updated_by', 'id');
    }

    /**
     * Returns the action Column html for datatables.
     *
     * @param  \App\User
     * @return  string
     */
    public static function laratablesCustomAction($role)
    {
        $data = new stdClass();
        $data->user = $role;
        $data->model = 'role';
        $data->edit_url = 'role.edit';
        $data->delete_url = 'role.destroy';
        return view('action', compact('data'))->render();
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Support\Facades\Validator;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('permission:add_role', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_role',   ['only' => ['edit', 'update']]);
        $this->middleware('permission:show_role',   ['only' => ['show', 'index']]);
        $this->middleware('permission:delete_role',   ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('role.index');
    }

    /**
     * return a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function data()
    {
        return Laratables::recordsOf(Role::class);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::where('parent_id', '')->with('children')->get();

        return view('role.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255', 'unique:roles'],
            'permissions' => ['required', 'array', 'min:1'],
        ])->validate();

        $role = new Role();
        $role->name = $request->name;
        $role->guard_name = 'web';
        $role->created_by = auth()->id();
        $role->save();

        $role->syncPermissions($request->permissions);

        return redirect()->route('role.index')->with('success', 'A new role created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::where('id', $id)->with('permissions')->firstOrFail();

        $permissions = Permission::where('parent_id', '')->with('children')->get();

        $role_permission = $role->permissions->pluck('id')->toArray();

        return view('role.edit', compact('permissions', 'role', 'role_permission'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255', 'unique:roles,name,' . $id],
            'permissions' => ['required', 'array', 'min:1'],
        ])->validate();

        $role = Role::findOrFail($id);
        $role->name = $request->name;
        $role->updated_by = auth()->id();
        $role->save();

        $role->syncPermissions($request->permissions);
        return redirect()->route('role.index')->with('success', 'Role information updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Role::destroy($id);
        return redirect()->route('role.index')->with('success', 'Role information deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/role/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Create Role') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-lg-8">
            <div class="card-body">
                <form method="POST" action="{{ route('role.store') }}">
                    @csrf
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Name') }}" />
        
                        <x-jet-input class="{{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name"
                                     :value="old('name')" required autofocus autocomplete="name" />
                        <x-jet-input-error for="name"></x-jet-input-error>
                    </div>
    
                    <h4 class="h4">
                        {{ __('Permissions: ') }}
                    </h4>
                    @if($errors->has('permissions'))
                        <span class="d-block invalid-feedback" role="alert">
                            <strong>{!! $errors->get('permissions')[0] !!}</strong>
                        </span>
                    @endif
                    <hr>

                    @foreach ($permissions as $permission)
                    <div class="form-group">
                            <h5>{{ $permission->name }}</h5>
                            <div class="row">
                                @foreach ($permission->children as $child)
                                    <div class="col-sm-6 col-md-4">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="permissions[]" id="ic_{{$child->id}}" value="{{ $child->id }}">
                                            <label class="custom-control-label" for="ic_{{$child->id}}">{{ ucwords(str_replace('_', ' ', $child->name))}}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <hr>
                        </div>
                    @endforeach
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('role.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/role/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit Role') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-lg-8">
            <div class="card-body">
                <form method="POST" action="{{ route('role.update', $role->id) }}">
                    @csrf
                    @method('PUT')
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Name') }}" />
        
                        <x-jet-input class="{{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name"
                                     :value="$role->name ?? old('name')" required autofocus autocomplete="name" />
                        <x-jet-input-error for="name"></x-jet-input-error>
                    </div>

                    <h4 class="h4">
                        {{ __('Permissions: ') }}
                    </h4>
                    @if($errors->has('permissions'))
                        <span class="d-block invalid-feedback" role="alert">
                            <strong>{!! $errors->get('permissions')[0] !!}</strong>
                        </span>
                    @endif
                    <hr>

                    @foreach ($permissions as $permission)
                        <div class="form-group">
                            <h5>{{ $permission->name }}</h5>
                            <div class="row">
                                @foreach ($permission->children as $child)
                                    <div class="col-sm-6 col-md-4">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" class="custom-control-input" name="permissions[]" id="ic_{{$child->id}}" value="{{ $child->id }}" @if(in_array($child->id, $role_permission)) checked @endif>
                                            <label class="custom-control-label" for="ic_{{$child->id}}">{{ ucwords(str_replace('_', ' ', $child->name))}}</label>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <hr>
                        </div>
                    @endforeach
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('role.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/role/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Role List') }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-12 align-self-end">
            <a class="btn btn-primary" href="{{ route('role.create') }}">
                {{ __('Create Role') }}
            </a>
        </div>
        <div class="col-12">
            <div class="mt-4">
                <table id="basic-laratable" class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Created User</th>
                            <th>Updated User</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    @push('style')
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    @push('scripts')
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
        {{-- <script src="//cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script> --}}

        <script>
            $(document).ready(function () {
                $.noConflict();
                $("#basic-laratable").DataTable({
                    serverSide: true,
                    ajax: "{{ route('role.data') }}",
                    columns: [
                        { name: 'name' },
                        { name: 'created_user.name', orderable: false },
                        { name: 'updated_user.name', orderable: false },
                        { name: 'created_at' },
                        { name: 'action', orderable: false, searchable:false},
                    ],
                });
            });
        </script>
    @endpush
</x-app-layout>