routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\TaskController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Duo2faController;
use App\Http\Controllers\SocialLoginController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\ShowActivityLogController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy-policy', function () {
    return view('policy');
});

Route::get('/terms-of-service', function () {
    return view('terms');
});

/* SOCIAL LOGIN ROUTES */
Route::get('social-login/{provider}', [SocialLoginController::class, 'redirect_to_provider'])->name('social-login.redirect');
Route::get('social-login/{provider}/callback', [SocialLoginController::class, 'callback_from_provider'])->name('social-login.callback');

Route::group(['middleware' => ['auth:sanctum', 'verified']], function () {
    /* DUO 2FA ROUTES */
    Route::get('/duo-2fa', [Duo2faController::class, 'resolve_duo_sign_request'])->name('duo.2fa');
    Route::post('/duo-2fa', [Duo2faController::class, 'resolve_duo_post_action']);

    Route::group(['middleware' => ['duo.2fa']], function () {
        /* DASHBOARD */
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        /* USER ROUTES */
        Route::get('user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('user', UserController::class);

        /* ACTIVITY LOG ROUTES */
        Route::get('activity-log', [ShowActivityLogController::class, 'index'])->name('activity-log.index');
        Route::get('activity-log/data', [ShowActivityLogController::class, 'data'])->name('activity-log.data');

        /* ROLE ROUTES */
        Route::get('role/data', [RoleController::class, 'data'])->name('role.data');
        Route::resource('role', RoleController::class);

        /* TASK ROUTES */
        Route::get('task/data', [TaskController::class, 'data'])->name('task.data');
        Route::resource('task', TaskController::class)->middleware('subscription.check');

        Route::get('subscription/payment', [SubscriptionController::class, 'subscription_payment'])->name('subscription.payment');
        Route::post('subscription/store', [SubscriptionController::class, 'subscription_store'])->name('subscription.store');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use stdClass;
use App\Models\Task;
use Laravel\Cashier\Billable;
use Laravel\Sanctum\HasApiTokens;
use Laravel\Jetstream\HasProfilePhoto;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use LogsActivity;
    use HasRoles;
    use Billable;

    /* USER STATUS */
    const ACTIVE = "active";
    const INACTIVE = "inactive";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'provider',
        'provider_id',
        'status'
    ];

    /* NAME OF THE LOG */
    protected static $logName = 'user';
    /* WHICH ATTRIBUTES WILL IGNORE WHILE LOGGING */
    protected static $ignoreChangedAttributes = ['password', 'updated_at'];
    /* LOGGING ONLY THE CHANGED ATTRIBUTES */
    protected static $logOnlyDirty = true;
    /* LOG FOR WHICH ATTRIBUTES  */
    protected static $logAttributes = ['name', 'email', 'status'];
    /* CUSTOM DESCRIPTION OF THE LOG */
    public function getDescriptionForEvent(string $eventName): string
    {
        return "User has been {$eventName}!";
    }

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    /**
     * An user has many tasks
     *
     * @return void
     */
    public function tasks()
    {
        return $this->hasMany(Task::class, 'user_id', 'id');
    }

    /**
     * Display currency symbol with format in salary column value.
     *
     * @param  \App\User
     * @return  string
     */
    public static function laratablesStatus($user)
    {
        return $user->status == self::ACTIVE ? "<span class='badge badge-success'>" . strtoupper($user->status) . "</span>" : "<span class='badge badge-danger'>" . strtoupper($user->status) . "</span>";
    }

    /**
     * Returns the action Column html for datatables.
     *
     * @param  \App\User
     * @return  string
     */
    public static function laratablesCustomAction($user)
    {
        $data = new stdClass();
        $data->user = $user;
        $data->model = 'user';
        $data->edit_url = 'user.edit';
        $data->delete_url = 'user.destroy';
        return view('action', compact('data'))->render();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Role;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Freshbitsweb\Laratables\Laratables;
use Illuminate\Support\Facades\Validator;


class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('permission:add_user', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_user',   ['only' => ['edit', 'update']]);
        $this->middleware('permission:show_user',   ['only' => ['show', 'index']]);
        $this->middleware('permission:delete_user',   ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.index');
    }

    /**
     * return a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function data()
    {
        return Laratables::recordsOf(User::class);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('user.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email:rfc,dns', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'max:30', 'confirmed'],
            'roles' => ['required', 'array', 'min:1'],
        ])->validate();

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'status' => $request->status,
        ]);

        $user->syncRoles($request->roles);

        return redirect()->route('user.index')->with('success', 'A new user created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        $user_role = $user->roles->pluck('id')->all();

        return view('user.edit', compact('user', 'roles', 'user_role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $user->id],
            'password' => ['nullable', 'string', 'min:8', 'max:30', 'confirmed'],
            'roles' => ['required', 'array', 'min:1'],
        ])->validate();

        $user->name = $request->name;
        $user->email = $request->email;
        if ($request->password) {
            $user->password = Hash::make($request->password);
        }
        $user->status = $request->status;

        $user->save();

        $user->syncRoles($request->roles);

        return redirect()->route('user.index')->with('success', 'User information updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('user.index')->with('success', 'User information deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Create User') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card-body">
                <form method="POST" action="{{ route('user.store') }}">
                    @csrf
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Name') }}" />
        
                        <x-jet-input class="{{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name"
                                     :value="old('name')" required autofocus autocomplete="name" />
                        <x-jet-input-error for="name"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Email') }}" />
        
                        <x-jet-input class="{{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email"
                                     :value="old('email')" required />
                        <x-jet-input-error for="email"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Password') }}" />
        
                        <x-jet-input class="{{ $errors->has('password') ? 'is-invalid' : '' }}" type="password"
                                     name="password" required autocomplete="new-password" />
                        <x-jet-input-error for="password"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Confirm Password') }}" />
        
                        <x-jet-input class="form-control" type="password" name="password_confirmation" required autocomplete="new-password" />
                    </div>
        
                    <div class="form-group">
                        <label for="select">{{ __('Role') }}</label>
       
                        <select name="roles[]" id="select" class="form-control" multiple required>
                            @foreach ($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->name }}</option>
                            @endforeach
                        </select>

                        @if($errors->has('roles'))
                            <span class="d-block invalid-feedback" role="alert">
                                <strong>{!! $errors->get('roles')[0] !!}</strong>
                            </span>
                        @endif
                    </div>
        
                    <div class="form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="active" value="active" name="status" class="custom-control-input" checked>
                            <label class="custom-control-label" for="active">ACTIVE</label>
                          </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="inactive" value="inactive" name="status" class="custom-control-input">
                            <label class="custom-control-label" for="inactive">INACTIVE</label>
                          </div>
                    </div>
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('user.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Edit User') }}
        </h2>
    </x-slot>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <div class="card-body">
                <form method="POST" action="{{ route('user.update', $user->id) }}">
                    @csrf
                    @method('PUT')
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Name') }}" />
        
                        <x-jet-input class="{{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name"
                                     :value="$user->name ?? old('name')" required autofocus autocomplete="name" />
                        <x-jet-input-error for="name"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Email') }}" />
        
                        <x-jet-input class="{{ $errors->has('email') ? 'is-invalid' : '' }}" type="email" name="email"
                                     :value="$user->email ?? old('email')" required />
                        <x-jet-input-error for="email"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Password') }}" />
        
                        <x-jet-input class="{{ $errors->has('password') ? 'is-invalid' : '' }}" type="password"
                                     name="password" autocomplete="new-password" />
                        <x-jet-input-error for="password"></x-jet-input-error>
                    </div>
        
                    <div class="form-group">
                        <x-jet-label value="{{ __('Confirm Password') }}" />
        
                        <x-jet-input class="form-control" type="password" name="password_confirmation" autocomplete="new-password" />
                    </div>

                    <div class="form-group">
                        <label for="select">{{ __('Role') }}</label>
       
                        <select name="roles[]" id="select" class="form-control" multiple required>
                            @foreach ($roles as $role)
                                <option value="{{ $role->id }}" {{ in_array($role->id, $user_role) ? 'selected' : '' }}>{{ $role->name }}</option>
                            @endforeach
                        </select>

                        @if($errors->has('roles'))
                            <span class="d-block invalid-feedback" role="alert">
                                <strong>{!! $errors->get('roles')[0] !!}</strong>
                            </span>
                        @endif
                    </div>
        
                    <div class="form-group">
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="active" value="active" name="status" class="custom-control-input" {{ $user->status == App\Models\User::ACTIVE ? 'checked' : ''}}>
                            <label class="custom-control-label" for="active">ACTIVE</label>
                          </div>
                        <div class="custom-control custom-radio custom-control-inline">
                            <input type="radio" id="inactive" value="inactive" name="status" class="custom-control-input" {{ $user->status == App\Models\User::INACTIVE ? 'checked' : ''}}>
                            <label class="custom-control-label" for="inactive">INACTIVE</label>
                          </div>
                    </div>
        
                    <div class="mb-0">
                        <div class="d-flex justify-content-end align-items-baseline">
                            <x-jet-button class="mr-2">
                                {{ __('Submit') }}
                            </x-jet-button>
                            <a class="btn btn-danger" href="{{ route('user.index') }}">
                                {{ __('Back') }}
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('User List') }}
        </h2>
    </x-slot>
    <div class="row">
        <div class="col-12 align-self-end">
            <a class="btn btn-primary" href="{{ route('user.create') }}">
                {{ __('Create User') }}
            </a>
        </div>
        <div class="col-12">
            <div class="mt-4">
                <table id="basic-laratable" class="table table-bordered table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

    @push('style')
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css">
    @endpush

    @push('scripts')
        <script src="//ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
        {{-- <script src="//cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script> --}}

        <script>
            $(document).ready(function () {
                $.noConflict();
                $("#basic-laratable").DataTable({
                    serverSide: true,
                    ajax: "{{ route('user.data') }}",
                    columns: [
                        { name: 'name' },
                        { name: 'email' },
                        { name: 'status' },
                        { name: 'created_at' },
                        { name: 'action', orderable: false, searchable:false},
                    ],
                });
            });
        </script>
    @endpush
</x-app-layout>